"""GitHub Search API source."""

from __future__ import annotations

import os
from dataclasses import dataclass

import httpx

GITHUB_API = "https://api.github.com/search/repositories"

# GitHub auto-generates repo names using adjective-noun patterns.
# These repos are typically empty/template projects, not real competitors.
_GITHUB_AUTO_ADJECTIVES = {
    "redesigned", "sturdy", "fuzzy", "bug-free", "shiny", "turbo",
    "legendary", "supreme", "verbose", "miniature", "psychic", "organic",
    "animated", "automatic", "bookish", "curly", "effective", "fantastic",
    "glowing", "humble", "ideal", "jubilant", "laughing", "musical",
    "obscure", "probable", "probable", "scaling", "special", "upgraded",
    "vigilant", "literate", "cautious", "congenial", "didactic", "eloquent",
    "fictional", "improved", "symmetrical", "refactored", "reimagined",
}
_GITHUB_AUTO_NOUNS = {
    "pancake", "adventure", "broccoli", "disco", "enigma", "fiesta",
    "guacamole", "happiness", "journey", "lamp", "memory", "noodle",
    "octo", "palm", "robot", "spoon", "telegram", "umbrella", "waffle",
    "barnacle", "chainsaw", "dollop", "eureka", "fishstick", "goggles",
    "tribble", "rotary-phone", "sniffle", "waddle", "doodle",
}


def _is_autogenerated_name(repo_name: str) -> bool:
    """Detect GitHub auto-generated repository names (adjective-noun pattern)."""
    # repo_name is "owner/repo-name", extract repo part
    parts = repo_name.split("/")
    if len(parts) < 2:
        return False
    name = parts[1].lower()
    tokens = name.replace("_", "-").split("-")
    if len(tokens) == 2:
        return tokens[0] in _GITHUB_AUTO_ADJECTIVES or tokens[1] in _GITHUB_AUTO_NOUNS
    return False


def _is_noise_repo(
    repo: dict,
    query_keywords: list[str] | None = None,
) -> bool:
    """Filter out low-quality repos that pollute competitor results.

    Args:
        repo: Repository dict with name, description, stars.
        query_keywords: If provided, repos whose description contains NONE
            of these keywords are treated as noise (unless >1000 stars).
    """
    name = repo.get("name", "")
    desc = repo.get("description", "")
    stars = repo.get("stars", 0)

    # Auto-generated GitHub names
    if _is_autogenerated_name(name):
        return True

    # No description + low stars = likely empty/abandoned
    if not desc.strip() and stars < 500:
        return True

    # Repo name is just a single character or number
    repo_part = name.split("/")[-1] if "/" in name else name
    if len(repo_part) <= 2:
        return True

    # Description relevance: if keywords provided, description must contain
    # at least one keyword. High-star repos (>1000) are exempt since they
    # may use different terminology for the same domain.
    if query_keywords and desc.strip() and stars < 1000:
        desc_lower = desc.lower()
        if not any(kw.lower() in desc_lower for kw in query_keywords):
            return True

    return False


@dataclass
class GitHubResults:
    """Aggregated GitHub search results across keyword variants."""

    total_repo_count: int
    max_stars: int
    top_repos: list[dict]


def _headers() -> dict[str, str]:
    headers = {"Accept": "application/vnd.github+json"}
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers


async def search_github_repos(keywords: list[str]) -> GitHubResults:
    """Search GitHub for repositories matching keyword variants.

    Args:
        keywords: List of search query strings (typically 3 variants).

    Returns:
        Aggregated results with total count, max stars, and top 5 repos.
    """
    max_total_count = 0
    max_stars = 0
    all_repos: list[dict] = []

    # Track how many queries each repo matched (relevance signal)
    repo_query_hits: dict[str, int] = {}

    async with httpx.AsyncClient(timeout=15.0) as client:
        for query in keywords:
            try:
                resp = await client.get(
                    GITHUB_API,
                    params={"q": query, "sort": "stars", "order": "desc", "per_page": 5},
                    headers=_headers(),
                )
                resp.raise_for_status()
                data = resp.json()
                query_count = data.get("total_count", 0)
                if query_count > max_total_count:
                    max_total_count = query_count

                for item in data.get("items", []):
                    name = item.get("full_name", "")
                    if not name:
                        continue
                    stars = item.get("stargazers_count", 0)
                    if stars > max_stars:
                        max_stars = stars
                    repo_query_hits[name] = repo_query_hits.get(name, 0) + 1
                    all_repos.append({
                        "name": name,
                        "url": item.get("html_url", ""),
                        "stars": stars,
                        "updated": item.get("updated_at", ""),
                        "description": (item.get("description") or "")[:200],
                    })
            except httpx.HTTPError:
                continue

    # Filter noise repos before ranking.
    # Build keyword list from query strings for relevance check.
    kw_set: set[str] = set()
    for q in keywords:
        for w in q.lower().split():
            if len(w) >= 4:
                kw_set.add(w)
    relevance_kws = list(kw_set) or None
    all_repos = [r for r in all_repos if not _is_noise_repo(r, query_keywords=relevance_kws)]

    # Deduplicate by name and sort by relevance (query hits) then stars.
    # Repos matching multiple query variants are more likely to be relevant.
    seen = set()
    unique_repos = []
    for repo in sorted(
        all_repos,
        key=lambda r: (repo_query_hits.get(r["name"], 0), r["stars"]),
        reverse=True,
    ):
        if repo["name"] not in seen:
            seen.add(repo["name"])
            unique_repos.append(repo)

    return GitHubResults(
        total_repo_count=max_total_count,
        max_stars=max_stars,
        top_repos=unique_repos[:5],
    )
