"""GitHub Search API source."""

from __future__ import annotations

import asyncio
import logging
import os
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone

import httpx

logger = logging.getLogger(__name__)

# Log whether GITHUB_TOKEN is configured (at import time)
if os.environ.get("GITHUB_TOKEN"):
    logger.info("GITHUB_TOKEN is set — authenticated GitHub API requests enabled")
else:
    logger.warning("GITHUB_TOKEN is NOT set — GitHub API requests will be unauthenticated (60 req/hr limit)")

GITHUB_API = "https://api.github.com/search/repositories"

# GitHub auto-generates repo names using adjective-noun patterns.
# These repos are typically empty/template projects, not real competitors.
_GITHUB_AUTO_ADJECTIVES = {
    "redesigned", "sturdy", "fuzzy", "bug-free", "shiny", "turbo",
    "legendary", "supreme", "verbose", "miniature", "psychic", "organic",
    "animated", "automatic", "bookish", "curly", "effective", "fantastic",
    "glowing", "humble", "ideal", "jubilant", "laughing", "musical",
    "obscure", "probable", "scaling", "special", "upgraded",
    "vigilant", "literate", "cautious", "congenial", "didactic", "eloquent",
    "fictional", "improved", "symmetrical", "refactored", "reimagined",
}
_GITHUB_AUTO_NOUNS = {
    "pancake", "adventure", "broccoli", "disco", "enigma", "fiesta",
    "guacamole", "happiness", "journey", "lamp", "memory", "noodle",
    "octo", "palm", "robot", "spoon", "telegram", "umbrella", "waffle",
    "barnacle", "chainsaw", "dollop", "eureka", "fishstick", "goggles",
    "tribble", "rotary-phone", "sniffle", "waddle", "doodle",
}


def _is_autogenerated_name(repo_name: str) -> bool:
    """Detect GitHub auto-generated repository names (adjective-noun pattern)."""
    # repo_name is "owner/repo-name", extract repo part
    parts = repo_name.split("/")
    if len(parts) < 2:
        return False
    name = parts[1].lower()
    tokens = name.replace("_", "-").split("-")
    if len(tokens) == 2:
        return tokens[0] in _GITHUB_AUTO_ADJECTIVES or tokens[1] in _GITHUB_AUTO_NOUNS
    return False


def _is_noise_repo(
    repo: dict,
    query_keywords: list[str] | None = None,
) -> bool:
    """Filter out low-quality repos that pollute competitor results.

    Args:
        repo: Repository dict with name, description, stars.
        query_keywords: If provided, repos whose description contains NONE
            of these keywords are treated as noise (unless >1000 stars).
    """
    name = repo.get("name", "")
    desc = repo.get("description", "")
    stars = repo.get("stars", 0)

    # Auto-generated GitHub names
    if _is_autogenerated_name(name):
        return True

    # No description + low stars = likely empty/abandoned
    if not desc.strip() and stars < 500:
        return True

    # Repo name is just a single character or number
    repo_part = name.split("/")[-1] if "/" in name else name
    if len(repo_part) <= 2:
        return True

    # Description relevance: if keywords provided, description must contain
    # at least one keyword. High-star repos (>1000) are exempt since they
    # may use different terminology for the same domain.
    if query_keywords and desc.strip() and stars < 1000:
        desc_lower = desc.lower()
        if not any(kw.lower() in desc_lower for kw in query_keywords):
            return True

    return False


@dataclass
class GitHubResults:
    """Aggregated GitHub search results across keyword variants."""

    total_repo_count: int
    max_stars: int
    top_repos: list[dict]
    recent_created_count: int = 0
    recent_ratio: float = 0.0
    recently_updated_ratio: float = 0.0


def _headers() -> dict[str, str]:
    headers = {"Accept": "application/vnd.github+json"}
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers


def _normalize_query(query: str) -> str:
    """Normalize query for GitHub search — replace hyphens with spaces.

    LLM-generated keywords often use hyphen-slug format (e.g. 'voice-scheduling-agent')
    but GitHub search works better with spaces.
    """
    return query.replace("-", " ")


async def _github_get_with_retry(
    client: httpx.AsyncClient,
    params: dict,
    *,
    max_retries: int = 2,
    label: str = "",
) -> httpx.Response:
    """GET GitHub API with retry on 403/429 (rate limit).

    Raises httpx.HTTPStatusError after all retries are exhausted.
    """
    delays = [1.0, 2.0]  # exponential-ish backoff
    last_exc: Exception | None = None
    for attempt in range(1 + max_retries):
        resp = await client.get(GITHUB_API, params=params, headers=_headers())
        if resp.status_code not in (403, 429):
            resp.raise_for_status()
            return resp
        # Rate-limited — decide whether to retry
        last_exc = httpx.HTTPStatusError(
            f"GitHub {resp.status_code}", request=resp.request, response=resp
        )
        if attempt < max_retries:
            delay = delays[attempt]
            logger.warning(
                "GitHub API %d for query %r (attempt %d/%d) — retrying in %.1fs",
                resp.status_code, label, attempt + 1, 1 + max_retries, delay,
            )
            await asyncio.sleep(delay)
        else:
            logger.error(
                "GitHub API %d for query %r — all %d attempts exhausted",
                resp.status_code, label, 1 + max_retries,
            )
    raise last_exc  # type: ignore[misc]


async def search_github_repos(keywords: list[str]) -> GitHubResults:
    """Search GitHub for repositories matching keyword variants.

    Args:
        keywords: List of search query strings (typically 3 variants).

    Returns:
        Aggregated results with total count, max stars, and top 5 repos.
    """
    normalized_keywords = list(dict.fromkeys(k.strip() for k in keywords if k.strip()))
    if not normalized_keywords:
        return GitHubResults(total_repo_count=0, max_stars=0, top_repos=[])

    max_total_count = 0
    max_stars = 0
    all_repos: list[dict] = []
    max_recent_created = 0

    six_months_ago = datetime.now(timezone.utc) - timedelta(days=180)
    created_since = six_months_ago.strftime("%Y-%m-%d")

    # Track how many queries each repo matched (relevance signal)
    repo_query_hits: dict[str, int] = {}

    async with httpx.AsyncClient(timeout=15.0) as client:
        # Fire the per-keyword requests CONCURRENTLY instead of sequentially — this loop was the
        # dominant latency in quick mode (2 requests × N keywords, serial, ~1s each). Bounded by a
        # semaphore to stay under GitHub's secondary rate limit on bursts.
        sem = asyncio.Semaphore(5)

        async def _main_search(query: str):
            search_q = _normalize_query(query)
            async with sem:
                try:
                    resp = await _github_get_with_retry(
                        client,
                        params={"q": search_q, "sort": "stars", "order": "desc", "per_page": 5},
                        label=search_q,
                    )
                    return resp.json()
                except httpx.HTTPError as exc:
                    logger.warning("GitHub search failed for query %r: %s", search_q, exc)
                    return None

        async def _recent_search(query: str):
            search_q = _normalize_query(query)
            async with sem:
                try:
                    recent_q = f"{search_q} created:>{created_since}"
                    resp = await _github_get_with_retry(
                        client,
                        params={"q": recent_q, "sort": "stars", "order": "desc", "per_page": 1},
                        label=f"{search_q} (recent)",
                    )
                    return resp.json().get("total_count", 0)
                except httpx.HTTPError as exc:
                    logger.warning("GitHub recent-search failed for query %r: %s", search_q, exc)
                    return 0

        main_results, recent_results = await asyncio.gather(
            asyncio.gather(*[_main_search(q) for q in normalized_keywords]),
            asyncio.gather(*[_recent_search(q) for q in normalized_keywords]),
        )

        for data in main_results:
            if not data:
                continue
            query_count = data.get("total_count", 0)
            if query_count > max_total_count:
                max_total_count = query_count
            for item in data.get("items", []):
                name = item.get("full_name", "")
                if not name:
                    continue
                stars = item.get("stargazers_count", 0)
                if stars > max_stars:
                    max_stars = stars
                repo_query_hits[name] = repo_query_hits.get(name, 0) + 1
                all_repos.append({
                    "name": name,
                    "url": item.get("html_url", ""),
                    "stars": stars,
                    "updated": item.get("updated_at", ""),
                    "description": (item.get("description") or "")[:200],
                })

        for recent_count in recent_results:
            if recent_count and recent_count > max_recent_created:
                max_recent_created = recent_count

    # Filter noise repos before ranking.
    # Build keyword list from query strings for relevance check.
    kw_set: set[str] = set()
    for q in normalized_keywords:
        for w in q.lower().split():
            if len(w) >= 4:
                kw_set.add(w)
    relevance_kws = list(kw_set) or None
    all_repos = [r for r in all_repos if not _is_noise_repo(r, query_keywords=relevance_kws)]

    # Deduplicate by name and sort by relevance (query hits) then stars.
    # Repos matching multiple query variants are more likely to be relevant.
    seen = set()
    unique_repos = []
    for repo in sorted(
        all_repos,
        key=lambda r: (repo_query_hits.get(r["name"], 0), r["stars"]),
        reverse=True,
    ):
        if repo["name"] not in seen:
            seen.add(repo["name"])
            unique_repos.append(repo)

    top_5 = unique_repos[:5]

    # recently_updated_ratio: fraction of top repos updated within 6 months
    recently_updated = 0
    for repo in top_5:
        updated_str = repo.get("updated", "")
        if updated_str:
            try:
                updated_dt = datetime.fromisoformat(updated_str.replace("Z", "+00:00"))
                if updated_dt >= six_months_ago:
                    recently_updated += 1
            except (ValueError, TypeError):
                pass
    recently_updated_ratio = recently_updated / len(top_5) if top_5 else 0.0

    # recent_ratio: recent_created / total (capped at 1.0)
    recent_ratio = (
        min(max_recent_created / max_total_count, 1.0)
        if max_total_count > 0
        else 0.0
    )

    return GitHubResults(
        total_repo_count=max_total_count,
        max_stars=max_stars,
        top_repos=top_5,
        recent_created_count=max_recent_created,
        recent_ratio=recent_ratio,
        recently_updated_ratio=recently_updated_ratio,
    )
